"""Assemble full BKBS export package on disk + zip."""

from __future__ import annotations

import json
import shutil
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy.orm import Session

from app.config import settings
from app.models import Entity, Export, Site
from app.services.export_graph import build_graph
from app.services.export_jsonld import (
    build_agent_json,
    build_organization_jsonld,
    build_services_jsonld,
)
from app.services.export_llms import render_llms_full, render_llms_txt


def _write_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _robots_suggestion(site: Site) -> str:
    return f"""# Suggested robots.txt additions for BKBS / AI agents
# Merge carefully with your existing robots.txt

User-agent: *
Allow: /

# Explicitly allow common AI crawlers if desired
User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: Google-Extended
Allow: /

Sitemap: {site.base_url}/sitemap.xml
"""


def _sitemap_suggestion(site: Site, entities: list[Entity]) -> str:
    urls = {site.base_url, f"{site.base_url}/llms.txt", f"{site.base_url}/graph.json"}
    for e in entities:
        for ev in e.evidence or []:
            if isinstance(ev, dict) and ev.get("url"):
                urls.add(ev["url"])
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for u in sorted(urls):
        lines.append("  <url>")
        lines.append(f"    <loc>{u}</loc>")
        lines.append("  </url>")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def _readme(site: Site) -> str:
    return f"""# BKBS Export Package — {site.name}

Generated by BKBS Converter for `{site.base_url}`.

## Deploy these files to your origin website

| File | Deploy to |
|------|-----------|
| `llms.txt` | `/llms.txt` |
| `llms-full.txt` | `/llms-full.txt` (optional) |
| `graph.json` | `/graph.json` or `/knowledge/graph.json` |
| `schema/organization.jsonld` | `/schema/organization.jsonld` or embed in HTML |
| `schema/services.jsonld` | `/schema/services.jsonld` |
| `.well-known/agent.json` | `/.well-known/agent.json` |
| `robots.txt.suggestion` | Merge into `/robots.txt` |
| `sitemap.xml.suggestion` | Merge into `/sitemap.xml` |

## Human vs machine

- Humans continue browsing your normal HTML pages.
- AI agents should prefer `llms.txt`, JSON-LD, and `graph.json`.

## Verification

Only **approved** entities are included unless this package was built with include_pending=true.

## Next steps

1. Review entity statuses in the BKBS Converter UI.
2. Re-export after approving changes.
3. Automate rescan in the converter when site content changes.
"""


def create_export_package(
    db: Session,
    site: Site,
    include_pending: bool = False,
) -> Export:
    query = db.query(Entity).filter(Entity.site_id == site.id)
    if include_pending:
        query = query.filter(Entity.status.in_(["approved", "pending", "needs_edit"]))
    else:
        query = query.filter(Entity.status == "approved")
    entities = query.order_by(Entity.entity_type, Entity.name).all()

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out_dir = settings.exports_dir / site.id / stamp
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Core files
    (out_dir / "llms.txt").write_text(render_llms_txt(site, entities), encoding="utf-8")
    (out_dir / "llms-full.txt").write_text(render_llms_full(site, entities), encoding="utf-8")
    _write_json(out_dir / "graph.json", build_graph(site, entities))
    _write_json(out_dir / "schema" / "organization.jsonld", build_organization_jsonld(site, entities))
    _write_json(out_dir / "schema" / "services.jsonld", build_services_jsonld(site, entities))
    _write_json(out_dir / ".well-known" / "agent.json", build_agent_json(site, entities))
    (out_dir / "robots.txt.suggestion").write_text(_robots_suggestion(site), encoding="utf-8")
    (out_dir / "sitemap.xml.suggestion").write_text(_sitemap_suggestion(site, entities), encoding="utf-8")
    (out_dir / "README.md").write_text(_readme(site), encoding="utf-8")

    # Zip
    zip_path = out_dir.with_suffix(".zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in out_dir.rglob("*"):
            if path.is_file():
                zf.write(path, arcname=str(path.relative_to(out_dir)))

    # latest pointer
    latest = settings.exports_dir / site.id / "latest"
    if latest.exists() or latest.is_symlink():
        if latest.is_symlink() or latest.is_file():
            latest.unlink()
        else:
            shutil.rmtree(latest)
    try:
        latest.symlink_to(out_dir, target_is_directory=True)
    except OSError:
        shutil.copytree(out_dir, latest)

    export = Export(
        site_id=site.id,
        path=str(out_dir),
        include_pending=include_pending,
        entity_count=len(entities),
    )
    db.add(export)
    db.commit()
    db.refresh(export)
    return export


def zip_path_for_export(export: Export) -> Path:
    p = Path(export.path)
    z = p.with_suffix(".zip")
    if z.exists():
        return z
    # rebuild zip if missing
    if p.exists():
        with zipfile.ZipFile(z, "w", zipfile.ZIP_DEFLATED) as zf:
            for path in p.rglob("*"):
                if path.is_file():
                    zf.write(path, arcname=str(path.relative_to(p)))
        return z
    raise FileNotFoundError(f"Export path missing: {export.path}")
