"""Generate llms.txt and llms-full.txt from BKBS entities."""

from __future__ import annotations

from app.constants import ENTITY_TYPE_LABELS
from app.models import Entity, Site


def _entities_by_type(entities: list[Entity]) -> dict[str, list[Entity]]:
    grouped: dict[str, list[Entity]] = {}
    for e in entities:
        grouped.setdefault(e.entity_type, []).append(e)
    for k in grouped:
        grouped[k] = sorted(grouped[k], key=lambda x: x.name.lower())
    return grouped


def render_llms_txt(site: Site, entities: list[Entity]) -> str:
    grouped = _entities_by_type(entities)
    identity = (grouped.get("business_identity") or [None])[0]

    title = identity.name if identity else site.name
    blurb = ""
    if identity and identity.description:
        blurb = identity.description.strip()
    elif identity and identity.properties:
        blurb = str(identity.properties.get("description") or "")

    lines = [
        f"# {title}",
        "",
    ]
    if blurb:
        lines.append(f"> {blurb}")
        lines.append("")

    lines.append("## About")
    lines.append(
        f"{title} publishes a Business Knowledge Base Standard (BKBS) machine layer "
        f"for AI agents. Canonical site: {site.base_url}"
    )
    lines.append("")

    # Contact from identity properties
    if identity and identity.properties:
        props = identity.properties
        contact_bits = []
        if props.get("email"):
            contact_bits.append(f"- Email: {props['email']}")
        if props.get("telephone"):
            contact_bits.append(f"- Phone: {props['telephone']}")
        if props.get("areaServed"):
            contact_bits.append(f"- Service Area: {props['areaServed']}")
        if props.get("openingHours"):
            contact_bits.append(f"- Operating Hours: {props['openingHours']}")
        if contact_bits:
            lines.append("## Contact & Locations")
            lines.extend(contact_bits)
            lines.append("")

    section_order = [
        "capability",
        "product_service",
        "facility_served",
        "expertise",
        "operational_problem",
        "project",
        "policy",
        "team",
        "asset",
        "knowledge_article",
    ]
    for etype in section_order:
        items = grouped.get(etype) or []
        if not items:
            continue
        lines.append(f"## {ENTITY_TYPE_LABELS.get(etype, etype)}")
        for e in items[:50]:
            desc = (e.description or "").strip().replace("\n", " ")
            if len(desc) > 180:
                desc = desc[:177] + "..."
            link = site.base_url
            if e.evidence:
                for ev in e.evidence:
                    if isinstance(ev, dict) and ev.get("url"):
                        link = ev["url"]
                        break
            if desc:
                lines.append(f"- [{e.name}]({link}): {desc}")
            else:
                lines.append(f"- [{e.name}]({link})")
        lines.append("")

    lines.append("## Documentation")
    lines.append(f"- [Full knowledge graph]({site.base_url}/graph.json) (deploy from BKBS export)")
    lines.append(f"- [llms-full.txt]({site.base_url}/llms-full.txt)")
    lines.append("")
    lines.append("<!-- Generated by BKBS Converter -->")
    return "\n".join(lines).rstrip() + "\n"


def render_llms_full(site: Site, entities: list[Entity]) -> str:
    """Richer dump: all entities with properties and relationships."""
    lines = [
        f"# {site.name} — BKBS Full Machine Dump",
        "",
        f"Base URL: {site.base_url}",
        f"Entity count: {len(entities)}",
        "",
    ]
    grouped = _entities_by_type(entities)
    for etype, label in ENTITY_TYPE_LABELS.items():
        items = grouped.get(etype) or []
        if not items:
            continue
        lines.append(f"## {label}")
        lines.append("")
        for e in items:
            lines.append(f"### {e.name}")
            lines.append(f"- id: {e.id}")
            lines.append(f"- type: {e.entity_type}")
            lines.append(f"- status: {e.status}")
            lines.append(f"- version: {e.version}")
            lines.append(f"- trust_level: {e.trust_level}")
            if e.description:
                lines.append(f"- description: {e.description.strip()}")
            if e.properties:
                lines.append(f"- properties: {e.properties}")
            if e.relationships:
                lines.append(f"- relationships: {e.relationships}")
            if e.evidence:
                lines.append(f"- evidence: {e.evidence}")
            lines.append("")
    lines.append("<!-- Generated by BKBS Converter -->")
    return "\n".join(lines).rstrip() + "\n"
