"""Origin audit after a successful crawl+merge. Read-only; never writes origin files."""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

import httpx

from app.config import settings
from app.services.crawler import USER_AGENT, assert_url_allowed, same_origin

FINDING_IDS = ("jsonld-on-page", "aipref-robots", "llms-txt", "agent-json", "tdmrep")
STATUSES = ("pass", "fail", "unknown")

LLMS_MARKER = "<!-- Generated by Manifest BKBS Converter -->"
AGENT_REQUIRED = ("name", "url", "knowledge")
AGENT_FORBIDDEN = ("protocol", "endpoint", "capabilities")
PROBE_TIMEOUT_S = 10.0
PROBE_MAX_REDIRECTS = 5
SKIP_AFTER_TRANSPORT = 2
SKIP_ERROR = "skipped after 2 connect failures"

_DEFAULT_SEVERITY = {
    "jsonld-on-page": "high",
    "aipref-robots": "info",
    "llms-txt": "high",
    "agent-json": "info",
    "tdmrep": "info",
}

_UNKNOWN_TITLES = {
    "jsonld-on-page": "JSON-LD on origin not checked",
    "aipref-robots": "Origin robots.txt not checked",
    "llms-txt": "Origin /llms.txt not checked",
    "agent-json": "Origin agent.json not checked",
    "tdmrep": "TDMRep not on origin (not required)",
}


@dataclass
class Probe:
    url: str
    status_code: int | None  # HTTP code, or None on transport error
    body: str | None = None
    error: str | None = None  # short transport message; not a stack trace

    @property
    def bytes(self) -> int:
        return len((self.body or "").encode("utf-8"))

    def as_stats(self) -> dict[str, Any]:
        return {
            "url": self.url,
            "status": self.status_code,
            "bytes": self.bytes,
            "error": self.error,
        }


@dataclass
class OriginProbes:
    robots: Probe | None = None
    llms_txt: Probe | None = None
    agent_json: Probe | None = None
    tdmrep: Probe | None = None

    def as_stats(self) -> dict[str, Any]:
        out: dict[str, Any] = {}
        for key in ("llms_txt", "agent_json", "robots", "tdmrep"):
            probe: Probe | None = getattr(self, key)
            if probe is not None:
                out[key] = probe.as_stats()
        ok = 0
        for key in ("llms_txt", "agent_json"):
            probe = getattr(self, key)
            if probe is not None and probe.status_code == 200:
                ok += 1
        out["origin_files_ok"] = ok
        return out


@dataclass
class AuditInput:
    base_url: str
    site_id: str  # for cta_href
    pages_json_ld: list[tuple[str, list]]  # (url, parsed blocks)
    html_ok_count: int
    robots: Probe | None
    llms_txt: Probe | None
    agent_json: Probe | None
    tdmrep: Probe | None = None


def has_high_severity_fail(findings: list[dict[str, Any]]) -> bool:
    return any(f.get("severity") == "high" and f.get("status") == "fail" for f in findings)


def unknown_findings(reason: str) -> list[dict[str, Any]]:
    evidence = f"audit error: {_short(reason)}"
    return [
        _finding(
            fid,
            severity=_DEFAULT_SEVERITY[fid],
            title=_UNKNOWN_TITLES[fid],
            evidence=evidence,
            status="unknown",
        )
        for fid in FINDING_IDS
    ]


def evaluate_findings(inp: AuditInput) -> list[dict[str, Any]]:
    return [
        _eval_jsonld(inp),
        _eval_aipref(inp),
        _eval_llms(inp),
        _eval_agent(inp),
        _eval_tdmrep(inp),
    ]


def probe_url(url: str) -> Probe:
    try:
        assert_url_allowed(url)
    except Exception as exc:
        return Probe(url=url, status_code=None, error=_short(str(exc)))
    headers = {"User-Agent": USER_AGENT, "Accept": "*/*"}
    timeout = httpx.Timeout(PROBE_TIMEOUT_S)
    try:
        with httpx.Client(
            headers=headers,
            timeout=timeout,
            follow_redirects=True,
            max_redirects=PROBE_MAX_REDIRECTS,
        ) as client:
            resp = client.get(url)
            final = str(resp.url) if resp.url is not None else url
            try:
                assert_url_allowed(final)
            except Exception as exc:
                return Probe(url=url, status_code=None, error=_short(str(exc)))
            if not same_origin(url, final):
                return Probe(url=url, status_code=None, error="redirect off-origin")
            body = resp.content[: settings.max_page_bytes]
            try:
                text = body.decode(resp.encoding or "utf-8", errors="replace")
            except Exception:
                text = body.decode("utf-8", errors="replace")
            return Probe(url=url, status_code=resp.status_code, body=text, error=None)
    except Exception as exc:
        return Probe(url=url, status_code=None, body=None, error=_short(str(exc)))


def probe_origin(base_url: str, robots_raw: str | None = None) -> OriginProbes:
    base = base_url.rstrip("/")
    out = OriginProbes()
    consecutive = 0
    skip = False

    def _next(url: str) -> Probe:
        nonlocal consecutive, skip
        if skip:
            return Probe(url=url, status_code=None, error=SKIP_ERROR)
        probe = probe_url(url)
        if _is_transport_fail(probe):
            consecutive += 1
            if consecutive >= SKIP_AFTER_TRANSPORT:
                skip = True
        else:
            consecutive = 0
        return probe

    robots_url = f"{base}/robots.txt"
    if robots_raw is not None:
        out.robots = Probe(url=robots_url, status_code=200, body=robots_raw)
    else:
        out.robots = _next(robots_url)
    out.llms_txt = _next(f"{base}/llms.txt")
    out.agent_json = _next(f"{base}/.well-known/agent.json")
    out.tdmrep = _next(f"{base}/.well-known/tdmrep.json")
    return out


def _finding(
    fid: str,
    *,
    severity: str,
    title: str,
    evidence: str,
    status: str,
    cta: str = "",
    cta_href: str = "",
) -> dict[str, Any]:
    return {
        "id": fid,
        "severity": severity,
        "title": title,
        "evidence": evidence,
        "status": status,
        "cta": cta,
        "cta_href": cta_href,
    }


def _short(err: str) -> str:
    return err.replace("\n", " ").strip()[:200]


def _is_transport_fail(probe: Probe) -> bool:
    return probe.status_code is None and bool(probe.error) and probe.error != SKIP_ERROR


def _jsonld_type(blocks: list) -> str:
    for block in blocks:
        if not isinstance(block, dict):
            continue
        raw = block.get("@type")
        if isinstance(raw, list):
            if raw:
                return str(raw[0])
            continue
        if raw:
            return str(raw)
    return "untyped"


def _eval_jsonld(inp: AuditInput) -> dict[str, Any]:
    ok_pages = inp.html_ok_count
    homepage = inp.pages_json_ld[0][0] if inp.pages_json_ld else inp.base_url
    if ok_pages <= 0:
        return _finding(
            "jsonld-on-page",
            severity="high",
            title="JSON-LD on origin not checked",
            evidence="0 HTML pages fetched",
            status="unknown",
        )
    n = 0
    first_url = None
    first_type = "untyped"
    for url, blocks in inp.pages_json_ld:
        if blocks:
            n += 1
            if first_url is None:
                first_url = url
                first_type = _jsonld_type(blocks)
    if n > 0:
        return _finding(
            "jsonld-on-page",
            severity="high",
            title="Origin HTML contains JSON-LD",
            evidence=(
                f"{n} of {ok_pages} pages have JSON-LD. "
                f"First hit: {first_url} @type={first_type}"
            ),
            status="pass",
        )
    return _finding(
        "jsonld-on-page",
        severity="high",
        title="Origin HTML has no JSON-LD",
        evidence=f"{n} of {ok_pages} pages have JSON-LD. Homepage {homepage}.",
        status="fail",
        cta="Copy JSON-LD snippet",
        cta_href=f"/sites/{inp.site_id}#machine-layers",
    )


def _aipref_line(body: str) -> str | None:
    for line in body.splitlines():
        lower = line.lower()
        if "content-usage" in lower or "aipref" in lower:
            return line.strip()[:200]
    return None


def _eval_aipref(inp: AuditInput) -> dict[str, Any]:
    probe = inp.robots
    url = probe.url if probe else f"{inp.base_url.rstrip('/')}/robots.txt"
    if probe is None or probe.status_code is None:
        err = _short(probe.error) if probe and probe.error else "not fetched"
        evidence = f"{url} error: {err}" if probe and probe.error else f"error: {err}"
        return _finding(
            "aipref-robots",
            severity="info",
            title="Origin robots.txt not checked",
            evidence=evidence,
            status="unknown",
        )
    if probe.status_code != 200:
        return _finding(
            "aipref-robots",
            severity="info",
            title="Origin robots.txt not checked",
            evidence=f"{url} HTTP {probe.status_code}",
            status="unknown",
        )
    line = _aipref_line(probe.body or "")
    if line:
        return _finding(
            "aipref-robots",
            severity="info",
            title="Origin robots.txt has Content-Usage / AIPREF",
            evidence=f"{line}; {url} HTTP 200",
            status="pass",
            cta="Origin already has Content-Usage — confirm it matches your toggles",
            cta_href=f"/sites/{inp.site_id}#machine-layers",
        )
    return _finding(
        "aipref-robots",
        severity="info",
        title="AIPREF not on origin robots (opt-in; default)",
        evidence=f"{url} HTTP 200, no Content-Usage / AIPREF line",
        status="fail",
        cta="Leave AIPREF off unless intended",
        cta_href=f"/sites/{inp.site_id}#machine-layers",
    )


def _eval_llms(inp: AuditInput) -> dict[str, Any]:
    probe = inp.llms_txt
    url = probe.url if probe else f"{inp.base_url.rstrip('/')}/llms.txt"
    # 1. Transport error
    if probe is None or probe.status_code is None:
        err = _short(probe.error) if probe and probe.error else "not fetched"
        return _finding(
            "llms-txt",
            severity="high",
            title="Origin /llms.txt not checked",
            evidence=f"{url} error: {err}",
            status="unknown",
        )
    body = probe.body or ""
    # 2. Non-200 or empty body
    if probe.status_code != 200 or not body:
        return _finding(
            "llms-txt",
            severity="high",
            title="Origin /llms.txt is not fetchable",
            evidence=f"{url} HTTP {probe.status_code}, {probe.bytes} bytes",
            status="fail",
            cta="Publish live",
            cta_href=f"/sites/{inp.site_id}",
        )
    stripped = body.lstrip()
    # 3. Markdown/BKBS body
    if stripped.startswith("#") or LLMS_MARKER in body:
        return _finding(
            "llms-txt",
            severity="high",
            title="Origin /llms.txt is fetchable",
            evidence=f"{url} HTTP 200, {probe.bytes} bytes",
            status="pass",
        )
    # HTML (even if the word "llms" appears) and any other 200 body → fail
    return _finding(
        "llms-txt",
        severity="high",
        title="Origin /llms.txt is not fetchable",
        evidence=f"{url} HTTP {probe.status_code}, {probe.bytes} bytes",
        status="fail",
        cta="Publish live",
        cta_href=f"/sites/{inp.site_id}",
    )


def _eval_agent(inp: AuditInput) -> dict[str, Any]:
    probe = inp.agent_json
    url = probe.url if probe else f"{inp.base_url.rstrip('/')}/.well-known/agent.json"
    if probe is None or probe.status_code is None:
        err = _short(probe.error) if probe and probe.error else "not fetched"
        return _finding(
            "agent-json",
            severity="info",
            title="Origin agent.json not checked",
            evidence=f"{url} error: {err}",
            status="unknown",
        )
    body = (probe.body or "").strip()
    if probe.status_code != 200 or not body:
        return _finding(
            "agent-json",
            severity="medium",
            title="Origin agent.json is missing",
            evidence=f"{url} HTTP {probe.status_code}, {probe.bytes} bytes",
            status="fail",
            cta="Publish live",
            cta_href=f"/sites/{inp.site_id}",
        )
    try:
        data = json.loads(body)
    except json.JSONDecodeError:
        return _finding(
            "agent-json",
            severity="medium",
            title="Origin agent.json is missing",
            evidence=f"{url} HTTP {probe.status_code}, {probe.bytes} bytes",
            status="fail",
            cta="Publish live",
            cta_href=f"/sites/{inp.site_id}",
        )
    if not isinstance(data, dict):
        return _finding(
            "agent-json",
            severity="medium",
            title="Origin agent.json is missing",
            evidence=f"{url} HTTP {probe.status_code}, {probe.bytes} bytes",
            status="fail",
            cta="Publish live",
            cta_href=f"/sites/{inp.site_id}",
        )
    forbidden = [k for k in AGENT_FORBIDDEN if k in data]
    if forbidden:
        return _finding(
            "agent-json",
            severity="high",
            title="Origin agent.json has a stub protocol",
            evidence=f"{url} HTTP 200; forbidden keys: {', '.join(forbidden)}",
            status="fail",
            cta="Republish — stub protocol detected",
            cta_href=f"/sites/{inp.site_id}#machine-layers",
        )
    if all(k in data for k in AGENT_REQUIRED):
        return _finding(
            "agent-json",
            severity="info",
            title="Origin agent.json is an honest knowledge index",
            evidence=f"{url} HTTP 200; keys name,url,knowledge",
            status="pass",
        )
    return _finding(
        "agent-json",
        severity="medium",
        title="Origin agent.json is missing",
        evidence=f"{url} HTTP {probe.status_code}, {probe.bytes} bytes",
        status="fail",
        cta="Publish live",
        cta_href=f"/sites/{inp.site_id}",
    )


def _eval_tdmrep(inp: AuditInput) -> dict[str, Any]:
    probe = inp.tdmrep
    url = probe.url if probe else f"{inp.base_url.rstrip('/')}/.well-known/tdmrep.json"
    if probe is not None and probe.status_code == 200:
        return _finding(
            "tdmrep",
            severity="info",
            title="Origin TDMRep file is present",
            evidence=f"{url} HTTP 200, {probe.bytes} bytes",
            status="pass",
            cta="Documented only — BKBS does not manage this file",
        )
    if probe is not None and probe.error and probe.status_code is None:
        evidence = f"{url} {probe.error}"
    elif probe is not None:
        evidence = f"{url} HTTP {probe.status_code}"
    else:
        evidence = f"{url} HTTP None"
    return _finding(
        "tdmrep",
        severity="info",
        title="TDMRep not on origin (not required)",
        evidence=evidence,
        status="unknown",
        cta="See INSTALL — do not auto-publish TDMRep opt-out",
    )
