<?php
declare(strict_types=1);

namespace Bkbs\Exports;

final class LlmsTxt
{
    /**
     * @param array<string, mixed> $site
     * @param list<array<string, mixed>> $entities
     */
    public static function render(array $site, array $entities): string
    {
        $name = $site['name'];
        $lines = ["# $name", '', "> Business knowledge package for AI agents.", '', '## About', "$name — " . ($site['base_url'] ?? ''), ''];
        $byType = [];
        foreach ($entities as $e) {
            $byType[$e['entity_type'] ?? 'other'][] = $e;
        }
        foreach (['capability' => 'Core Capabilities', 'product_service' => 'Products & Services', 'facility_served' => 'Facilities Served', 'policy' => 'Policies'] as $t => $label) {
            if (empty($byType[$t])) {
                continue;
            }
            $lines[] = '## ' . $label;
            foreach ($byType[$t] as $e) {
                $desc = trim((string) ($e['description'] ?? ''));
                $desc = $desc !== '' ? ': ' . str_replace("\n", ' ', mb_substr($desc, 0, 160)) : '';
                $lines[] = '- ' . $e['name'] . $desc;
            }
            $lines[] = '';
        }
        $lines[] = '## Documentation';
        $lines[] = '- graph.json (full knowledge graph)';
        $lines[] = '';
        $lines[] = '<!-- Generated by Manifest BKBS Converter PHP edition -->';
        return implode("\n", $lines) . "\n";
    }

    /**
     * @param array<string, mixed> $site
     * @param list<array<string, mixed>> $entities
     */
    public static function renderFull(array $site, array $entities): string
    {
        $lines = ["# {$site['name']} — BKBS Full Dump", '', 'Entities: ' . count($entities), ''];
        foreach ($entities as $e) {
            $lines[] = '## ' . ($e['name'] ?? '');
            $lines[] = '- type: ' . ($e['entity_type'] ?? '');
            $lines[] = '- status: ' . ($e['status'] ?? '');
            if (!empty($e['description'])) {
                $lines[] = '- description: ' . $e['description'];
            }
            $lines[] = '';
        }
        return implode("\n", $lines) . "\n";
    }
}
