<?php
declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit;
}

final class MBKBS_Export_Llms
{
    /**
     * @param list<array<string, mixed>> $entities
     */
    public static function render_txt(string $name, string $home, array $entities): string
    {
        $llms = ["# {$name}", '', '> Agent-ready knowledge published by Manifest BKBS Converter for WordPress.', '', '## About', "{$name} — {$home}", ''];
        $by = [];
        foreach ($entities as $e) {
            $by[$e['entity_type']][] = $e;
        }
        foreach (['capability' => 'Core Capabilities', 'product_service' => 'Products & Services', 'facility_served' => 'Facilities Served', 'policy' => 'Policies'] as $t => $label) {
            if (empty($by[$t])) {
                continue;
            }
            $llms[] = '## ' . $label;
            foreach ($by[$t] as $e) {
                $desc = trim((string) ($e['description'] ?? ''));
                $desc = $desc !== '' ? ': ' . str_replace("\n", ' ', substr($desc, 0, 160)) : '';
                $llms[] = '- ' . $e['name'] . $desc;
            }
            $llms[] = '';
        }
        $llms[] = '## Documentation';
        $llms[] = '- ' . $home . '/graph.json';
        $llms[] = '';
        $llms[] = '<!-- Generated by Manifest BKBS Converter for WordPress -->';
        return implode("\n", $llms) . "\n";
    }

    /**
     * @param list<array<string, mixed>> $entities
     */
    public static function render_full(string $name, array $entities): string
    {
        $full = ["# {$name} — BKBS Full Dump", '', 'Entities: ' . count($entities), ''];
        foreach ($entities as $e) {
            $full[] = '## ' . $e['name'];
            $full[] = '- type: ' . $e['entity_type'];
            $full[] = '- status: ' . $e['status'];
            if (!empty($e['description'])) {
                $full[] = '- description: ' . $e['description'];
            }
            $full[] = '';
        }
        return implode("\n", $full) . "\n";
    }
}
