<?php
declare(strict_types=1);

namespace Bkbs;

/** Origin audit after a successful crawl+upsert. Read-only; never writes origin files. */
final class ScanAudit
{
    public const FINDING_IDS = ['jsonld-on-page', 'aipref-robots', 'llms-txt', 'agent-json', 'tdmrep'];
    public const STATUSES = ['pass', 'fail', 'unknown'];
    public const LLMS_MARKER = '<!-- Generated by Manifest BKBS Converter -->';
    public const SKIP_ERROR = 'skipped after 2 connect failures';

    private const AGENT_REQUIRED = ['name', 'url', 'knowledge'];
    private const AGENT_FORBIDDEN = ['protocol', 'endpoint', 'capabilities'];
    private const SKIP_AFTER_TRANSPORT = 2;

    private const DEFAULT_SEVERITY = [
        'jsonld-on-page' => 'high',
        'aipref-robots' => 'info',
        'llms-txt' => 'high',
        'agent-json' => 'info',
        'tdmrep' => 'info',
    ];

    private const UNKNOWN_TITLES = [
        'jsonld-on-page' => 'JSON-LD on origin not checked',
        'aipref-robots' => 'Origin robots.txt not checked',
        'llms-txt' => 'Origin /llms.txt not checked',
        'agent-json' => 'Origin agent.json not checked',
        'tdmrep' => 'TDMRep not on origin (not required)',
    ];

    /**
     * @param list<array<string, mixed>> $findings
     */
    public static function hasHighSeverityFail(array $findings): bool
    {
        foreach ($findings as $f) {
            if (($f['severity'] ?? '') === 'high' && ($f['status'] ?? '') === 'fail') {
                return true;
            }
        }
        return false;
    }

    /**
     * @return list<array<string, mixed>>
     */
    public static function unknownFindings(string $reason): array
    {
        $evidence = 'audit error: ' . self::short($reason);
        $out = [];
        foreach (self::FINDING_IDS as $fid) {
            $out[] = self::finding(
                $fid,
                self::DEFAULT_SEVERITY[$fid],
                self::UNKNOWN_TITLES[$fid],
                $evidence,
                'unknown'
            );
        }
        return $out;
    }

    /**
     * @param array{
     *   base_url:string,
     *   site_id:string,
     *   pages_json_ld:list<array{0:string,1:list}>,
     *   html_ok_count:int,
     *   robots:?array,
     *   llms_txt:?array,
     *   agent_json:?array,
     *   tdmrep:?array
     * } $inp
     * @return list<array<string, mixed>>
     */
    public static function evaluateFindings(array $inp): array
    {
        return [
            self::evalJsonld($inp),
            self::evalAipref($inp),
            self::evalLlms($inp),
            self::evalAgent($inp),
            self::evalTdmrep($inp),
        ];
    }

    /**
     * GET robots.txt, /llms.txt, agent.json, tdmrep.json. Skip remaining after 2 transport failures.
     *
     * @param callable(string): array{status:int,body:string,final_url:string,error:?string}|null $requestFn
     * @return array{robots:?array,llms_txt:?array,agent_json:?array,tdmrep:?array}
     */
    public static function probeOrigin(string $baseUrl, ?string $robotsRaw = null, ?callable $requestFn = null): array
    {
        if ($requestFn === null) {
            $crawler = new Crawler();
            $requestFn = static function (string $url) use ($crawler): array {
                return $crawler->request($url);
            };
        }
        $base = rtrim($baseUrl, '/');
        $consecutive = 0;
        $skip = false;

        $next = static function (string $url) use ($requestFn, &$consecutive, &$skip): array {
            if ($skip) {
                return ['url' => $url, 'status' => null, 'body' => null, 'error' => self::SKIP_ERROR];
            }
            $res = $requestFn($url);
            $probe = self::requestToProbe($url, $res);
            if (self::isTransportFail($probe)) {
                $consecutive++;
                if ($consecutive >= self::SKIP_AFTER_TRANSPORT) {
                    $skip = true;
                }
            } else {
                $consecutive = 0;
            }
            return $probe;
        };

        $robotsUrl = $base . '/robots.txt';
        $robots = $robotsRaw !== null
            ? ['url' => $robotsUrl, 'status' => 200, 'body' => $robotsRaw, 'error' => null]
            : $next($robotsUrl);

        return [
            'robots' => $robots,
            'llms_txt' => $next($base . '/llms.txt'),
            'agent_json' => $next($base . '/.well-known/agent.json'),
            'tdmrep' => $next($base . '/.well-known/tdmrep.json'),
        ];
    }

    /**
     * @param array{robots?:?array,llms_txt?:?array,agent_json?:?array,tdmrep?:?array} $probes
     * @return array<string, mixed>
     */
    public static function probesAsStats(array $probes): array
    {
        $out = [];
        foreach (['llms_txt', 'agent_json', 'robots', 'tdmrep'] as $key) {
            if (!isset($probes[$key]) || !is_array($probes[$key])) {
                continue;
            }
            $p = $probes[$key];
            $out[$key] = [
                'url' => $p['url'] ?? '',
                'status' => $p['status'] ?? null,
                'bytes' => self::probeBytes($p),
                'error' => $p['error'] ?? null,
            ];
        }
        $ok = 0;
        foreach (['llms_txt', 'agent_json'] as $key) {
            if (($out[$key]['status'] ?? null) === 200) {
                $ok++;
            }
        }
        $out['origin_files_ok'] = $ok;
        return $out;
    }

    /**
     * @param array{status:int,body:string,final_url:string,error:?string} $res
     * @return array{url:string,status:?int,body:?string,error:?string}
     */
    private static function requestToProbe(string $url, array $res): array
    {
        $err = $res['error'] ?? null;
        if ($err !== null && $err !== '') {
            return ['url' => $url, 'status' => null, 'body' => null, 'error' => self::short((string) $err)];
        }
        $status = (int) ($res['status'] ?? 0);
        return [
            'url' => $url,
            'status' => $status > 0 ? $status : null,
            'body' => (string) ($res['body'] ?? ''),
            'error' => $status > 0 ? null : 'empty response',
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private static function finding(
        string $fid,
        string $severity,
        string $title,
        string $evidence,
        string $status,
        string $cta = '',
        string $ctaHref = ''
    ): array {
        return [
            'id' => $fid,
            'severity' => $severity,
            'title' => $title,
            'evidence' => $evidence,
            'status' => $status,
            'cta' => $cta,
            'cta_href' => $ctaHref,
        ];
    }

    private static function short(string $err): string
    {
        return substr(trim(str_replace("\n", ' ', $err)), 0, 200);
    }

    /** @param array<string, mixed> $probe */
    private static function isTransportFail(array $probe): bool
    {
        return ($probe['status'] ?? null) === null
            && !empty($probe['error'])
            && $probe['error'] !== self::SKIP_ERROR;
    }

    /** @param array<string, mixed>|null $probe */
    private static function probeBytes(?array $probe): int
    {
        return strlen((string) ($probe['body'] ?? ''));
    }

    /** @param list<mixed> $blocks */
    private static function jsonldType(array $blocks): string
    {
        foreach ($blocks as $block) {
            if (!is_array($block)) {
                continue;
            }
            $raw = $block['@type'] ?? null;
            if (is_array($raw)) {
                if ($raw) {
                    return (string) $raw[0];
                }
                continue;
            }
            if ($raw) {
                return (string) $raw;
            }
        }
        return 'untyped';
    }

    private static function siteHref(string $siteId, bool $machineLayers = false): string
    {
        $path = 'sites/' . $siteId;
        if (function_exists('url') && PHP_SAPI !== 'cli') {
            $href = \url($path);
        } else {
            $href = '/index.php?r=' . rawurlencode($path);
        }
        if ($machineLayers) {
            $href .= '#machine-layers';
        }
        return $href;
    }

    /** @param array<string, mixed> $inp */
    private static function evalJsonld(array $inp): array
    {
        $okPages = (int) ($inp['html_ok_count'] ?? 0);
        $pages = $inp['pages_json_ld'] ?? [];
        $homepage = $pages[0][0] ?? ($inp['base_url'] ?? '');
        if ($okPages <= 0) {
            return self::finding(
                'jsonld-on-page',
                'high',
                'JSON-LD on origin not checked',
                '0 HTML pages fetched',
                'unknown'
            );
        }
        $n = 0;
        $firstUrl = null;
        $firstType = 'untyped';
        foreach ($pages as $row) {
            $url = is_array($row) ? (string) ($row[0] ?? '') : '';
            $blocks = is_array($row) ? ($row[1] ?? []) : [];
            if (!is_array($blocks)) {
                $blocks = [];
            }
            if ($blocks) {
                $n++;
                if ($firstUrl === null) {
                    $firstUrl = $url;
                    $firstType = self::jsonldType($blocks);
                }
            }
        }
        if ($n > 0) {
            return self::finding(
                'jsonld-on-page',
                'high',
                'Origin HTML contains JSON-LD',
                "{$n} of {$okPages} pages have JSON-LD. First hit: {$firstUrl} @type={$firstType}",
                'pass'
            );
        }
        return self::finding(
            'jsonld-on-page',
            'high',
            'Origin HTML has no JSON-LD',
            "{$n} of {$okPages} pages have JSON-LD. Homepage {$homepage}.",
            'fail',
            'Copy JSON-LD snippet',
            self::siteHref((string) ($inp['site_id'] ?? ''), true)
        );
    }

    /** @param array<string, mixed> $inp */
    private static function evalAipref(array $inp): array
    {
        $probe = is_array($inp['robots'] ?? null) ? $inp['robots'] : null;
        $url = is_array($probe) && isset($probe['url'])
            ? (string) $probe['url']
            : (rtrim((string) ($inp['base_url'] ?? ''), '/') . '/robots.txt');
        if ($probe === null || ($probe['status'] ?? null) === null) {
            $rawErr = is_array($probe) ? (string) ($probe['error'] ?? '') : '';
            $err = self::short($rawErr !== '' ? $rawErr : 'not fetched');
            $evidence = ($rawErr !== '')
                ? "{$url} error: {$err}"
                : "error: {$err}";
            return self::finding(
                'aipref-robots',
                'info',
                'Origin robots.txt not checked',
                $evidence,
                'unknown'
            );
        }
        if ((int) $probe['status'] !== 200) {
            return self::finding(
                'aipref-robots',
                'info',
                'Origin robots.txt not checked',
                "{$url} HTTP {$probe['status']}",
                'unknown'
            );
        }
        $line = self::aiprefLine((string) ($probe['body'] ?? ''));
        $href = self::siteHref((string) ($inp['site_id'] ?? ''), true);
        if ($line !== null) {
            return self::finding(
                'aipref-robots',
                'info',
                'Origin robots.txt has Content-Usage / AIPREF',
                "{$line}; {$url} HTTP 200",
                'pass',
                'Origin already has Content-Usage — confirm it matches your toggles',
                $href
            );
        }
        return self::finding(
            'aipref-robots',
            'info',
            'AIPREF not on origin robots (opt-in; default)',
            "{$url} HTTP 200, no Content-Usage / AIPREF line",
            'fail',
            'Leave AIPREF off unless intended',
            $href
        );
    }

    private static function aiprefLine(string $body): ?string
    {
        foreach (preg_split('/\R/', $body) ?: [] as $line) {
            $lower = strtolower($line);
            if (str_contains($lower, 'content-usage') || str_contains($lower, 'aipref')) {
                return substr(trim($line), 0, 200);
            }
        }
        return null;
    }

    /** @param array<string, mixed> $inp */
    private static function evalLlms(array $inp): array
    {
        $probe = is_array($inp['llms_txt'] ?? null) ? $inp['llms_txt'] : null;
        $url = is_array($probe) && isset($probe['url'])
            ? (string) $probe['url']
            : (rtrim((string) ($inp['base_url'] ?? ''), '/') . '/llms.txt');
        $publish = self::siteHref((string) ($inp['site_id'] ?? ''), false);
        if ($probe === null || ($probe['status'] ?? null) === null) {
            $rawErr = is_array($probe) ? (string) ($probe['error'] ?? '') : '';
            $err = self::short($rawErr !== '' ? $rawErr : 'not fetched');
            return self::finding(
                'llms-txt',
                'high',
                'Origin /llms.txt not checked',
                "{$url} error: {$err}",
                'unknown'
            );
        }
        $body = (string) ($probe['body'] ?? '');
        if ((int) $probe['status'] !== 200 || $body === '') {
            return self::finding(
                'llms-txt',
                'high',
                'Origin /llms.txt is not fetchable',
                "{$url} HTTP {$probe['status']}, " . self::probeBytes($probe) . ' bytes',
                'fail',
                'Publish live',
                $publish
            );
        }
        $stripped = ltrim($body);
        if (str_starts_with($stripped, '#') || str_contains($body, self::LLMS_MARKER)) {
            return self::finding(
                'llms-txt',
                'high',
                'Origin /llms.txt is fetchable',
                "{$url} HTTP 200, " . self::probeBytes($probe) . ' bytes',
                'pass'
            );
        }
        return self::finding(
            'llms-txt',
            'high',
            'Origin /llms.txt is not fetchable',
            "{$url} HTTP {$probe['status']}, " . self::probeBytes($probe) . ' bytes',
            'fail',
            'Publish live',
            $publish
        );
    }

    /** @param array<string, mixed> $inp */
    private static function evalAgent(array $inp): array
    {
        $probe = is_array($inp['agent_json'] ?? null) ? $inp['agent_json'] : null;
        $url = is_array($probe) && isset($probe['url'])
            ? (string) $probe['url']
            : (rtrim((string) ($inp['base_url'] ?? ''), '/') . '/.well-known/agent.json');
        $publish = self::siteHref((string) ($inp['site_id'] ?? ''), false);
        $layers = self::siteHref((string) ($inp['site_id'] ?? ''), true);
        if ($probe === null || ($probe['status'] ?? null) === null) {
            $rawErr = is_array($probe) ? (string) ($probe['error'] ?? '') : '';
            $err = self::short($rawErr !== '' ? $rawErr : 'not fetched');
            return self::finding(
                'agent-json',
                'info',
                'Origin agent.json not checked',
                "{$url} error: {$err}",
                'unknown'
            );
        }
        $body = trim((string) ($probe['body'] ?? ''));
        $missing = static function () use ($url, $probe, $publish): array {
            return self::finding(
                'agent-json',
                'medium',
                'Origin agent.json is missing',
                "{$url} HTTP {$probe['status']}, " . self::probeBytes($probe) . ' bytes',
                'fail',
                'Publish live',
                $publish
            );
        };
        if ((int) $probe['status'] !== 200 || $body === '') {
            return $missing();
        }
        $data = json_decode($body, true);
        if (!is_array($data) || array_is_list($data)) {
            return $missing();
        }
        $forbidden = [];
        foreach (self::AGENT_FORBIDDEN as $k) {
            if (array_key_exists($k, $data)) {
                $forbidden[] = $k;
            }
        }
        if ($forbidden) {
            return self::finding(
                'agent-json',
                'high',
                'Origin agent.json has a stub protocol',
                "{$url} HTTP 200; forbidden keys: " . implode(', ', $forbidden),
                'fail',
                'Republish — stub protocol detected',
                $layers
            );
        }
        foreach (self::AGENT_REQUIRED as $k) {
            if (!array_key_exists($k, $data)) {
                return $missing();
            }
        }
        return self::finding(
            'agent-json',
            'info',
            'Origin agent.json is an honest knowledge index',
            "{$url} HTTP 200; keys name,url,knowledge",
            'pass'
        );
    }

    /** @param array<string, mixed> $inp */
    private static function evalTdmrep(array $inp): array
    {
        $probe = is_array($inp['tdmrep'] ?? null) ? $inp['tdmrep'] : null;
        $url = is_array($probe) && isset($probe['url'])
            ? (string) $probe['url']
            : (rtrim((string) ($inp['base_url'] ?? ''), '/') . '/.well-known/tdmrep.json');
        if ($probe !== null && ($probe['status'] ?? null) === 200) {
            return self::finding(
                'tdmrep',
                'info',
                'Origin TDMRep file is present',
                "{$url} HTTP 200, " . self::probeBytes($probe) . ' bytes',
                'pass',
                'Documented only — BKBS does not manage this file'
            );
        }
        if ($probe !== null && !empty($probe['error']) && ($probe['status'] ?? null) === null) {
            $evidence = $url . ' ' . $probe['error'];
        } elseif ($probe !== null) {
            $evidence = $url . ' HTTP ' . ($probe['status'] ?? 'None');
        } else {
            $evidence = $url . ' HTTP None';
        }
        return self::finding(
            'tdmrep',
            'info',
            'TDMRep not on origin (not required)',
            $evidence,
            'unknown',
            'See INSTALL — do not auto-publish TDMRep opt-out'
        );
    }
}
